---

- debug: var=app_healthcheck_url verbosity=1

- name: "Heathcheck | Wait for {{ app_name }} to be healthy"
  uri:
    url: "{{ app_healthcheck_url }}"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 15
  delay: 5
