---
# tasks file for role_spring_boot_app

- import_tasks: prerequisites.yml

- import_tasks: requirements.yml

- name: Set application destination folder
  set_fact:
    app_artifact_destination_folder: "{{ applications_root_folder }}/{{ app_name | upper }}/{{ app_version }}"

- name: Set artifact destination file
  set_fact:
    app_artifact_destination_file: "{{ app_artifact_destination_folder }}/{{ app_artifact_id }}-{{ app_version }}.{{ app_extension }}"

- name: " Service | Check if use systemd"
  set_fact: use_system_d={{ (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) }}

- import_tasks: install.yml
  when: >
        app_state == 'present'

- import_tasks: uninstall.yml
  when: >
        app_state == 'absent'

- meta: flush_handlers

- import_tasks: healthcheck.yml
  when: >
        app_healthcheck_url is defined and
        app_healthcheck_url|length > 0 and
        app_state == 'present'
