---
- name: Converge
  hosts: all
  vars:
    sb_java_package: java-1.8.0-openjdk
    sb_user_groups_definitions:
      - name: sbgroup
    sb_users_definition:
      - name: Simple Spring boot App User
        username: sbuser
        groups: [sbgroup]
  roles:
    - role: ansible-role-springboot
      # sb_app_state: absent
      sb_app_as_a_service: true
      sb_app_name: dummy-boot-app
      sb_app_group_id: fr.chidix
      sb_app_artifact_id: dummy-boot-app
      sb_app_version: 0.0.1-SNAPSHOT
      sb_app_extension: jar
      sb_app_user: sbuser
      sb_app_user_group: sbgroup
      sb_maven_repository_url: https://nexus3.apps.osocloud.chidix.fr/repository/maven-snapshots/
      sb_app_repository_username: test
      sb_app_repository_password: test
      # sb_applications_root_folder: /opt/applis
      sb_local_maven_artifact_dowload: false
      # sb_app_service_debug: true
      sb_app_config_file_template_path: "{{ playbook_dir }}/templates/dummy-boot-app-configuration.yml.j2"
      sb_app_healthcheck_urls:
        - "http://localhost:8082/actuator/health"
      sb_app_healthcheck_ports:
        - 8082
