---
- name: Converge
  hosts: all
  vars:
    sb_user_groups_definitions:
      - name: sbgroup
    sb_users_definition:
      - name: Simple Spring boot App User
        username: sbuser
        groups: [sbgroup]
  roles:
    - role: ansible-role-springboot
      # sb_app_state: absent
      # sb_app_stop_wait_time: 30
      sb_app_name: simple-springboot-app
      sb_app_as_a_service: true
      sb_app_group_id: fr.runadium
      sb_app_artifact_id: simple-springboot-app
      sb_app_version: 0.0.1-SNAPSHOT
      sb_app_extension: jar
      sb_app_user: sbuser
      sb_app_user_group: sbgroup
      # sb_app_service_java_home
      # sb_maven_repository_url: http://repo1.maven.org/maven2
      # sb_applications_root_folder: /opt/applis
      sb_local_maven_artifact_dowload: false
      # the test spring-boot application source is https://github.com/runadium/simple-springboot-app
      sb_app_artifact_file: "{{ playbook_dir}}/artifacts/simple-springboot-app-0.0.1-SNAPSHOT.jar"
      # sb_app_service_debug: true
      sb_app_config_file_template_path: "{{ playbook_dir }}/templates/simple-springboot-app-configuration.yml.j2"
      sb_app_config_file_final_name: application.yml
      sb_app_logback_file_template_path: "{{ playbook_dir }}/templates/logback.xml.j2"
      sb_app_java_opts_others: "-Djavax.net.debug=all -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6006"
      sb_app_healthcheck_urls:
        - "https://localhost:8443/actuator/health"
        - "http://localhost:8080/actuator/health"
      sb_app_healthcheck_ports:
        - 8080
        - 8443
      sb_app_env: []
